# Generated by Django 4.0.3 on 2022-04-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
