# Generated by Django 4.0.3 on 2022-04-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsproject', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='projecturl',
            field=models.URLField(default=''),
        ),
    ]
