# Generated by Django 4.0.3 on 2022-04-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsproject', '0005_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.CharField(default='design', max_length=20),
        ),
        migrations.AddField(
            model_name='rating',
            name='scale',
            field=models.IntegerField(default=1),
        ),
    ]
