# Generated by Django 4.0.3 on 2022-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsproject', '0007_alter_rating_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='design_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='usability_rating',
            field=models.IntegerField(default=1),
        ),
    ]
