# Generated by Django 4.0.3 on 2022-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsproject', '0008_post_content_rating_post_design_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='design_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='usability_rating',
            field=models.IntegerField(default=0),
        ),
    ]
